# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Declaration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unknown_fields': 'UnknownFieldSet',
        'repeated': 'bool',
        'default_instance_for_type': 'Declaration',
        'parser_for_type': 'ParserDeclaration',
        'serialized_size': 'int',
        'reserved': 'bool',
        'full_name_bytes': 'ByteString',
        'type_bytes': 'ByteString',
        'initialized': 'bool',
        'type': 'str',
        'number': 'int',
        'full_name': 'str',
        'initialization_error_string': 'str',
        'descriptor_for_type': 'Descriptor',
        'all_fields': 'dict(str, object)',
        'memoized_serialized_size': 'int'
    }

    attribute_map = {
        'unknown_fields': 'unknownFields',
        'repeated': 'repeated',
        'default_instance_for_type': 'defaultInstanceForType',
        'parser_for_type': 'parserForType',
        'serialized_size': 'serializedSize',
        'reserved': 'reserved',
        'full_name_bytes': 'fullNameBytes',
        'type_bytes': 'typeBytes',
        'initialized': 'initialized',
        'type': 'type',
        'number': 'number',
        'full_name': 'fullName',
        'initialization_error_string': 'initializationErrorString',
        'descriptor_for_type': 'descriptorForType',
        'all_fields': 'allFields',
        'memoized_serialized_size': 'memoizedSerializedSize'
    }

    def __init__(self, unknown_fields=None, repeated=None, default_instance_for_type=None, parser_for_type=None, serialized_size=None, reserved=None, full_name_bytes=None, type_bytes=None, initialized=None, type=None, number=None, full_name=None, initialization_error_string=None, descriptor_for_type=None, all_fields=None, memoized_serialized_size=None):  # noqa: E501
        """Declaration - a model defined in Swagger"""  # noqa: E501
        self._unknown_fields = None
        self._repeated = None
        self._default_instance_for_type = None
        self._parser_for_type = None
        self._serialized_size = None
        self._reserved = None
        self._full_name_bytes = None
        self._type_bytes = None
        self._initialized = None
        self._type = None
        self._number = None
        self._full_name = None
        self._initialization_error_string = None
        self._descriptor_for_type = None
        self._all_fields = None
        self._memoized_serialized_size = None
        self.discriminator = None
        if unknown_fields is not None:
            self.unknown_fields = unknown_fields
        if repeated is not None:
            self.repeated = repeated
        if default_instance_for_type is not None:
            self.default_instance_for_type = default_instance_for_type
        if parser_for_type is not None:
            self.parser_for_type = parser_for_type
        if serialized_size is not None:
            self.serialized_size = serialized_size
        if reserved is not None:
            self.reserved = reserved
        if full_name_bytes is not None:
            self.full_name_bytes = full_name_bytes
        if type_bytes is not None:
            self.type_bytes = type_bytes
        if initialized is not None:
            self.initialized = initialized
        if type is not None:
            self.type = type
        if number is not None:
            self.number = number
        if full_name is not None:
            self.full_name = full_name
        if initialization_error_string is not None:
            self.initialization_error_string = initialization_error_string
        if descriptor_for_type is not None:
            self.descriptor_for_type = descriptor_for_type
        if all_fields is not None:
            self.all_fields = all_fields
        if memoized_serialized_size is not None:
            self.memoized_serialized_size = memoized_serialized_size

    @property
    def unknown_fields(self):
        """Gets the unknown_fields of this Declaration.  # noqa: E501


        :return: The unknown_fields of this Declaration.  # noqa: E501
        :rtype: UnknownFieldSet
        """
        return self._unknown_fields

    @unknown_fields.setter
    def unknown_fields(self, unknown_fields):
        """Sets the unknown_fields of this Declaration.


        :param unknown_fields: The unknown_fields of this Declaration.  # noqa: E501
        :type: UnknownFieldSet
        """

        self._unknown_fields = unknown_fields

    @property
    def repeated(self):
        """Gets the repeated of this Declaration.  # noqa: E501


        :return: The repeated of this Declaration.  # noqa: E501
        :rtype: bool
        """
        return self._repeated

    @repeated.setter
    def repeated(self, repeated):
        """Sets the repeated of this Declaration.


        :param repeated: The repeated of this Declaration.  # noqa: E501
        :type: bool
        """

        self._repeated = repeated

    @property
    def default_instance_for_type(self):
        """Gets the default_instance_for_type of this Declaration.  # noqa: E501


        :return: The default_instance_for_type of this Declaration.  # noqa: E501
        :rtype: Declaration
        """
        return self._default_instance_for_type

    @default_instance_for_type.setter
    def default_instance_for_type(self, default_instance_for_type):
        """Sets the default_instance_for_type of this Declaration.


        :param default_instance_for_type: The default_instance_for_type of this Declaration.  # noqa: E501
        :type: Declaration
        """

        self._default_instance_for_type = default_instance_for_type

    @property
    def parser_for_type(self):
        """Gets the parser_for_type of this Declaration.  # noqa: E501


        :return: The parser_for_type of this Declaration.  # noqa: E501
        :rtype: ParserDeclaration
        """
        return self._parser_for_type

    @parser_for_type.setter
    def parser_for_type(self, parser_for_type):
        """Sets the parser_for_type of this Declaration.


        :param parser_for_type: The parser_for_type of this Declaration.  # noqa: E501
        :type: ParserDeclaration
        """

        self._parser_for_type = parser_for_type

    @property
    def serialized_size(self):
        """Gets the serialized_size of this Declaration.  # noqa: E501


        :return: The serialized_size of this Declaration.  # noqa: E501
        :rtype: int
        """
        return self._serialized_size

    @serialized_size.setter
    def serialized_size(self, serialized_size):
        """Sets the serialized_size of this Declaration.


        :param serialized_size: The serialized_size of this Declaration.  # noqa: E501
        :type: int
        """

        self._serialized_size = serialized_size

    @property
    def reserved(self):
        """Gets the reserved of this Declaration.  # noqa: E501


        :return: The reserved of this Declaration.  # noqa: E501
        :rtype: bool
        """
        return self._reserved

    @reserved.setter
    def reserved(self, reserved):
        """Sets the reserved of this Declaration.


        :param reserved: The reserved of this Declaration.  # noqa: E501
        :type: bool
        """

        self._reserved = reserved

    @property
    def full_name_bytes(self):
        """Gets the full_name_bytes of this Declaration.  # noqa: E501


        :return: The full_name_bytes of this Declaration.  # noqa: E501
        :rtype: ByteString
        """
        return self._full_name_bytes

    @full_name_bytes.setter
    def full_name_bytes(self, full_name_bytes):
        """Sets the full_name_bytes of this Declaration.


        :param full_name_bytes: The full_name_bytes of this Declaration.  # noqa: E501
        :type: ByteString
        """

        self._full_name_bytes = full_name_bytes

    @property
    def type_bytes(self):
        """Gets the type_bytes of this Declaration.  # noqa: E501


        :return: The type_bytes of this Declaration.  # noqa: E501
        :rtype: ByteString
        """
        return self._type_bytes

    @type_bytes.setter
    def type_bytes(self, type_bytes):
        """Sets the type_bytes of this Declaration.


        :param type_bytes: The type_bytes of this Declaration.  # noqa: E501
        :type: ByteString
        """

        self._type_bytes = type_bytes

    @property
    def initialized(self):
        """Gets the initialized of this Declaration.  # noqa: E501


        :return: The initialized of this Declaration.  # noqa: E501
        :rtype: bool
        """
        return self._initialized

    @initialized.setter
    def initialized(self, initialized):
        """Sets the initialized of this Declaration.


        :param initialized: The initialized of this Declaration.  # noqa: E501
        :type: bool
        """

        self._initialized = initialized

    @property
    def type(self):
        """Gets the type of this Declaration.  # noqa: E501


        :return: The type of this Declaration.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Declaration.


        :param type: The type of this Declaration.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def number(self):
        """Gets the number of this Declaration.  # noqa: E501


        :return: The number of this Declaration.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this Declaration.


        :param number: The number of this Declaration.  # noqa: E501
        :type: int
        """

        self._number = number

    @property
    def full_name(self):
        """Gets the full_name of this Declaration.  # noqa: E501


        :return: The full_name of this Declaration.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this Declaration.


        :param full_name: The full_name of this Declaration.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def initialization_error_string(self):
        """Gets the initialization_error_string of this Declaration.  # noqa: E501


        :return: The initialization_error_string of this Declaration.  # noqa: E501
        :rtype: str
        """
        return self._initialization_error_string

    @initialization_error_string.setter
    def initialization_error_string(self, initialization_error_string):
        """Sets the initialization_error_string of this Declaration.


        :param initialization_error_string: The initialization_error_string of this Declaration.  # noqa: E501
        :type: str
        """

        self._initialization_error_string = initialization_error_string

    @property
    def descriptor_for_type(self):
        """Gets the descriptor_for_type of this Declaration.  # noqa: E501


        :return: The descriptor_for_type of this Declaration.  # noqa: E501
        :rtype: Descriptor
        """
        return self._descriptor_for_type

    @descriptor_for_type.setter
    def descriptor_for_type(self, descriptor_for_type):
        """Sets the descriptor_for_type of this Declaration.


        :param descriptor_for_type: The descriptor_for_type of this Declaration.  # noqa: E501
        :type: Descriptor
        """

        self._descriptor_for_type = descriptor_for_type

    @property
    def all_fields(self):
        """Gets the all_fields of this Declaration.  # noqa: E501


        :return: The all_fields of this Declaration.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._all_fields

    @all_fields.setter
    def all_fields(self, all_fields):
        """Sets the all_fields of this Declaration.


        :param all_fields: The all_fields of this Declaration.  # noqa: E501
        :type: dict(str, object)
        """

        self._all_fields = all_fields

    @property
    def memoized_serialized_size(self):
        """Gets the memoized_serialized_size of this Declaration.  # noqa: E501


        :return: The memoized_serialized_size of this Declaration.  # noqa: E501
        :rtype: int
        """
        return self._memoized_serialized_size

    @memoized_serialized_size.setter
    def memoized_serialized_size(self, memoized_serialized_size):
        """Sets the memoized_serialized_size of this Declaration.


        :param memoized_serialized_size: The memoized_serialized_size of this Declaration.  # noqa: E501
        :type: int
        """

        self._memoized_serialized_size = memoized_serialized_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Declaration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Declaration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
