# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class EnumDescriptor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'index': 'int',
        'proto': 'EnumDescriptorProto',
        'full_name': 'str',
        'file': 'FileDescriptor',
        'containing_type': 'Descriptor',
        'values': 'list[EnumValueDescriptor]',
        'closed': 'bool',
        'options': 'EnumOptions',
        'name': 'str'
    }

    attribute_map = {
        'index': 'index',
        'proto': 'proto',
        'full_name': 'fullName',
        'file': 'file',
        'containing_type': 'containingType',
        'values': 'values',
        'closed': 'closed',
        'options': 'options',
        'name': 'name'
    }

    def __init__(self, index=None, proto=None, full_name=None, file=None, containing_type=None, values=None, closed=None, options=None, name=None):  # noqa: E501
        """EnumDescriptor - a model defined in Swagger"""  # noqa: E501
        self._index = None
        self._proto = None
        self._full_name = None
        self._file = None
        self._containing_type = None
        self._values = None
        self._closed = None
        self._options = None
        self._name = None
        self.discriminator = None
        if index is not None:
            self.index = index
        if proto is not None:
            self.proto = proto
        if full_name is not None:
            self.full_name = full_name
        if file is not None:
            self.file = file
        if containing_type is not None:
            self.containing_type = containing_type
        if values is not None:
            self.values = values
        if closed is not None:
            self.closed = closed
        if options is not None:
            self.options = options
        if name is not None:
            self.name = name

    @property
    def index(self):
        """Gets the index of this EnumDescriptor.  # noqa: E501


        :return: The index of this EnumDescriptor.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this EnumDescriptor.


        :param index: The index of this EnumDescriptor.  # noqa: E501
        :type: int
        """

        self._index = index

    @property
    def proto(self):
        """Gets the proto of this EnumDescriptor.  # noqa: E501


        :return: The proto of this EnumDescriptor.  # noqa: E501
        :rtype: EnumDescriptorProto
        """
        return self._proto

    @proto.setter
    def proto(self, proto):
        """Sets the proto of this EnumDescriptor.


        :param proto: The proto of this EnumDescriptor.  # noqa: E501
        :type: EnumDescriptorProto
        """

        self._proto = proto

    @property
    def full_name(self):
        """Gets the full_name of this EnumDescriptor.  # noqa: E501


        :return: The full_name of this EnumDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this EnumDescriptor.


        :param full_name: The full_name of this EnumDescriptor.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def file(self):
        """Gets the file of this EnumDescriptor.  # noqa: E501


        :return: The file of this EnumDescriptor.  # noqa: E501
        :rtype: FileDescriptor
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this EnumDescriptor.


        :param file: The file of this EnumDescriptor.  # noqa: E501
        :type: FileDescriptor
        """

        self._file = file

    @property
    def containing_type(self):
        """Gets the containing_type of this EnumDescriptor.  # noqa: E501


        :return: The containing_type of this EnumDescriptor.  # noqa: E501
        :rtype: Descriptor
        """
        return self._containing_type

    @containing_type.setter
    def containing_type(self, containing_type):
        """Sets the containing_type of this EnumDescriptor.


        :param containing_type: The containing_type of this EnumDescriptor.  # noqa: E501
        :type: Descriptor
        """

        self._containing_type = containing_type

    @property
    def values(self):
        """Gets the values of this EnumDescriptor.  # noqa: E501


        :return: The values of this EnumDescriptor.  # noqa: E501
        :rtype: list[EnumValueDescriptor]
        """
        return self._values

    @values.setter
    def values(self, values):
        """Sets the values of this EnumDescriptor.


        :param values: The values of this EnumDescriptor.  # noqa: E501
        :type: list[EnumValueDescriptor]
        """

        self._values = values

    @property
    def closed(self):
        """Gets the closed of this EnumDescriptor.  # noqa: E501


        :return: The closed of this EnumDescriptor.  # noqa: E501
        :rtype: bool
        """
        return self._closed

    @closed.setter
    def closed(self, closed):
        """Sets the closed of this EnumDescriptor.


        :param closed: The closed of this EnumDescriptor.  # noqa: E501
        :type: bool
        """

        self._closed = closed

    @property
    def options(self):
        """Gets the options of this EnumDescriptor.  # noqa: E501


        :return: The options of this EnumDescriptor.  # noqa: E501
        :rtype: EnumOptions
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this EnumDescriptor.


        :param options: The options of this EnumDescriptor.  # noqa: E501
        :type: EnumOptions
        """

        self._options = options

    @property
    def name(self):
        """Gets the name of this EnumDescriptor.  # noqa: E501


        :return: The name of this EnumDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EnumDescriptor.


        :param name: The name of this EnumDescriptor.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EnumDescriptor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EnumDescriptor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
