# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MessageOptionsOrBuilder(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'deprecated': 'bool',
        'deprecated_legacy_json_field_conflicts': 'bool',
        'uninterpreted_option_or_builder_list': 'list[UninterpretedOptionOrBuilder]',
        'map_entry': 'bool',
        'features': 'FeatureSet',
        'no_standard_descriptor_accessor': 'bool',
        'features_or_builder': 'FeatureSetOrBuilder',
        'uninterpreted_option_list': 'list[UninterpretedOption]',
        'uninterpreted_option_count': 'int',
        'message_set_wire_format': 'bool',
        'default_instance_for_type': 'Message',
        'initialization_error_string': 'str',
        'descriptor_for_type': 'Descriptor',
        'all_fields': 'dict(str, object)',
        'unknown_fields': 'UnknownFieldSet',
        'initialized': 'bool'
    }

    attribute_map = {
        'deprecated': 'deprecated',
        'deprecated_legacy_json_field_conflicts': 'deprecatedLegacyJsonFieldConflicts',
        'uninterpreted_option_or_builder_list': 'uninterpretedOptionOrBuilderList',
        'map_entry': 'mapEntry',
        'features': 'features',
        'no_standard_descriptor_accessor': 'noStandardDescriptorAccessor',
        'features_or_builder': 'featuresOrBuilder',
        'uninterpreted_option_list': 'uninterpretedOptionList',
        'uninterpreted_option_count': 'uninterpretedOptionCount',
        'message_set_wire_format': 'messageSetWireFormat',
        'default_instance_for_type': 'defaultInstanceForType',
        'initialization_error_string': 'initializationErrorString',
        'descriptor_for_type': 'descriptorForType',
        'all_fields': 'allFields',
        'unknown_fields': 'unknownFields',
        'initialized': 'initialized'
    }

    def __init__(self, deprecated=None, deprecated_legacy_json_field_conflicts=None, uninterpreted_option_or_builder_list=None, map_entry=None, features=None, no_standard_descriptor_accessor=None, features_or_builder=None, uninterpreted_option_list=None, uninterpreted_option_count=None, message_set_wire_format=None, default_instance_for_type=None, initialization_error_string=None, descriptor_for_type=None, all_fields=None, unknown_fields=None, initialized=None):  # noqa: E501
        """MessageOptionsOrBuilder - a model defined in Swagger"""  # noqa: E501
        self._deprecated = None
        self._deprecated_legacy_json_field_conflicts = None
        self._uninterpreted_option_or_builder_list = None
        self._map_entry = None
        self._features = None
        self._no_standard_descriptor_accessor = None
        self._features_or_builder = None
        self._uninterpreted_option_list = None
        self._uninterpreted_option_count = None
        self._message_set_wire_format = None
        self._default_instance_for_type = None
        self._initialization_error_string = None
        self._descriptor_for_type = None
        self._all_fields = None
        self._unknown_fields = None
        self._initialized = None
        self.discriminator = None
        if deprecated is not None:
            self.deprecated = deprecated
        if deprecated_legacy_json_field_conflicts is not None:
            self.deprecated_legacy_json_field_conflicts = deprecated_legacy_json_field_conflicts
        if uninterpreted_option_or_builder_list is not None:
            self.uninterpreted_option_or_builder_list = uninterpreted_option_or_builder_list
        if map_entry is not None:
            self.map_entry = map_entry
        if features is not None:
            self.features = features
        if no_standard_descriptor_accessor is not None:
            self.no_standard_descriptor_accessor = no_standard_descriptor_accessor
        if features_or_builder is not None:
            self.features_or_builder = features_or_builder
        if uninterpreted_option_list is not None:
            self.uninterpreted_option_list = uninterpreted_option_list
        if uninterpreted_option_count is not None:
            self.uninterpreted_option_count = uninterpreted_option_count
        if message_set_wire_format is not None:
            self.message_set_wire_format = message_set_wire_format
        if default_instance_for_type is not None:
            self.default_instance_for_type = default_instance_for_type
        if initialization_error_string is not None:
            self.initialization_error_string = initialization_error_string
        if descriptor_for_type is not None:
            self.descriptor_for_type = descriptor_for_type
        if all_fields is not None:
            self.all_fields = all_fields
        if unknown_fields is not None:
            self.unknown_fields = unknown_fields
        if initialized is not None:
            self.initialized = initialized

    @property
    def deprecated(self):
        """Gets the deprecated of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The deprecated of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: bool
        """
        return self._deprecated

    @deprecated.setter
    def deprecated(self, deprecated):
        """Sets the deprecated of this MessageOptionsOrBuilder.


        :param deprecated: The deprecated of this MessageOptionsOrBuilder.  # noqa: E501
        :type: bool
        """

        self._deprecated = deprecated

    @property
    def deprecated_legacy_json_field_conflicts(self):
        """Gets the deprecated_legacy_json_field_conflicts of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The deprecated_legacy_json_field_conflicts of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: bool
        """
        return self._deprecated_legacy_json_field_conflicts

    @deprecated_legacy_json_field_conflicts.setter
    def deprecated_legacy_json_field_conflicts(self, deprecated_legacy_json_field_conflicts):
        """Sets the deprecated_legacy_json_field_conflicts of this MessageOptionsOrBuilder.


        :param deprecated_legacy_json_field_conflicts: The deprecated_legacy_json_field_conflicts of this MessageOptionsOrBuilder.  # noqa: E501
        :type: bool
        """

        self._deprecated_legacy_json_field_conflicts = deprecated_legacy_json_field_conflicts

    @property
    def uninterpreted_option_or_builder_list(self):
        """Gets the uninterpreted_option_or_builder_list of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The uninterpreted_option_or_builder_list of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: list[UninterpretedOptionOrBuilder]
        """
        return self._uninterpreted_option_or_builder_list

    @uninterpreted_option_or_builder_list.setter
    def uninterpreted_option_or_builder_list(self, uninterpreted_option_or_builder_list):
        """Sets the uninterpreted_option_or_builder_list of this MessageOptionsOrBuilder.


        :param uninterpreted_option_or_builder_list: The uninterpreted_option_or_builder_list of this MessageOptionsOrBuilder.  # noqa: E501
        :type: list[UninterpretedOptionOrBuilder]
        """

        self._uninterpreted_option_or_builder_list = uninterpreted_option_or_builder_list

    @property
    def map_entry(self):
        """Gets the map_entry of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The map_entry of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: bool
        """
        return self._map_entry

    @map_entry.setter
    def map_entry(self, map_entry):
        """Sets the map_entry of this MessageOptionsOrBuilder.


        :param map_entry: The map_entry of this MessageOptionsOrBuilder.  # noqa: E501
        :type: bool
        """

        self._map_entry = map_entry

    @property
    def features(self):
        """Gets the features of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The features of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: FeatureSet
        """
        return self._features

    @features.setter
    def features(self, features):
        """Sets the features of this MessageOptionsOrBuilder.


        :param features: The features of this MessageOptionsOrBuilder.  # noqa: E501
        :type: FeatureSet
        """

        self._features = features

    @property
    def no_standard_descriptor_accessor(self):
        """Gets the no_standard_descriptor_accessor of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The no_standard_descriptor_accessor of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: bool
        """
        return self._no_standard_descriptor_accessor

    @no_standard_descriptor_accessor.setter
    def no_standard_descriptor_accessor(self, no_standard_descriptor_accessor):
        """Sets the no_standard_descriptor_accessor of this MessageOptionsOrBuilder.


        :param no_standard_descriptor_accessor: The no_standard_descriptor_accessor of this MessageOptionsOrBuilder.  # noqa: E501
        :type: bool
        """

        self._no_standard_descriptor_accessor = no_standard_descriptor_accessor

    @property
    def features_or_builder(self):
        """Gets the features_or_builder of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The features_or_builder of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: FeatureSetOrBuilder
        """
        return self._features_or_builder

    @features_or_builder.setter
    def features_or_builder(self, features_or_builder):
        """Sets the features_or_builder of this MessageOptionsOrBuilder.


        :param features_or_builder: The features_or_builder of this MessageOptionsOrBuilder.  # noqa: E501
        :type: FeatureSetOrBuilder
        """

        self._features_or_builder = features_or_builder

    @property
    def uninterpreted_option_list(self):
        """Gets the uninterpreted_option_list of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The uninterpreted_option_list of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: list[UninterpretedOption]
        """
        return self._uninterpreted_option_list

    @uninterpreted_option_list.setter
    def uninterpreted_option_list(self, uninterpreted_option_list):
        """Sets the uninterpreted_option_list of this MessageOptionsOrBuilder.


        :param uninterpreted_option_list: The uninterpreted_option_list of this MessageOptionsOrBuilder.  # noqa: E501
        :type: list[UninterpretedOption]
        """

        self._uninterpreted_option_list = uninterpreted_option_list

    @property
    def uninterpreted_option_count(self):
        """Gets the uninterpreted_option_count of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The uninterpreted_option_count of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: int
        """
        return self._uninterpreted_option_count

    @uninterpreted_option_count.setter
    def uninterpreted_option_count(self, uninterpreted_option_count):
        """Sets the uninterpreted_option_count of this MessageOptionsOrBuilder.


        :param uninterpreted_option_count: The uninterpreted_option_count of this MessageOptionsOrBuilder.  # noqa: E501
        :type: int
        """

        self._uninterpreted_option_count = uninterpreted_option_count

    @property
    def message_set_wire_format(self):
        """Gets the message_set_wire_format of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The message_set_wire_format of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: bool
        """
        return self._message_set_wire_format

    @message_set_wire_format.setter
    def message_set_wire_format(self, message_set_wire_format):
        """Sets the message_set_wire_format of this MessageOptionsOrBuilder.


        :param message_set_wire_format: The message_set_wire_format of this MessageOptionsOrBuilder.  # noqa: E501
        :type: bool
        """

        self._message_set_wire_format = message_set_wire_format

    @property
    def default_instance_for_type(self):
        """Gets the default_instance_for_type of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The default_instance_for_type of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: Message
        """
        return self._default_instance_for_type

    @default_instance_for_type.setter
    def default_instance_for_type(self, default_instance_for_type):
        """Sets the default_instance_for_type of this MessageOptionsOrBuilder.


        :param default_instance_for_type: The default_instance_for_type of this MessageOptionsOrBuilder.  # noqa: E501
        :type: Message
        """

        self._default_instance_for_type = default_instance_for_type

    @property
    def initialization_error_string(self):
        """Gets the initialization_error_string of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The initialization_error_string of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: str
        """
        return self._initialization_error_string

    @initialization_error_string.setter
    def initialization_error_string(self, initialization_error_string):
        """Sets the initialization_error_string of this MessageOptionsOrBuilder.


        :param initialization_error_string: The initialization_error_string of this MessageOptionsOrBuilder.  # noqa: E501
        :type: str
        """

        self._initialization_error_string = initialization_error_string

    @property
    def descriptor_for_type(self):
        """Gets the descriptor_for_type of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The descriptor_for_type of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: Descriptor
        """
        return self._descriptor_for_type

    @descriptor_for_type.setter
    def descriptor_for_type(self, descriptor_for_type):
        """Sets the descriptor_for_type of this MessageOptionsOrBuilder.


        :param descriptor_for_type: The descriptor_for_type of this MessageOptionsOrBuilder.  # noqa: E501
        :type: Descriptor
        """

        self._descriptor_for_type = descriptor_for_type

    @property
    def all_fields(self):
        """Gets the all_fields of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The all_fields of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._all_fields

    @all_fields.setter
    def all_fields(self, all_fields):
        """Sets the all_fields of this MessageOptionsOrBuilder.


        :param all_fields: The all_fields of this MessageOptionsOrBuilder.  # noqa: E501
        :type: dict(str, object)
        """

        self._all_fields = all_fields

    @property
    def unknown_fields(self):
        """Gets the unknown_fields of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The unknown_fields of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: UnknownFieldSet
        """
        return self._unknown_fields

    @unknown_fields.setter
    def unknown_fields(self, unknown_fields):
        """Sets the unknown_fields of this MessageOptionsOrBuilder.


        :param unknown_fields: The unknown_fields of this MessageOptionsOrBuilder.  # noqa: E501
        :type: UnknownFieldSet
        """

        self._unknown_fields = unknown_fields

    @property
    def initialized(self):
        """Gets the initialized of this MessageOptionsOrBuilder.  # noqa: E501


        :return: The initialized of this MessageOptionsOrBuilder.  # noqa: E501
        :rtype: bool
        """
        return self._initialized

    @initialized.setter
    def initialized(self, initialized):
        """Sets the initialized of this MessageOptionsOrBuilder.


        :param initialized: The initialized of this MessageOptionsOrBuilder.  # noqa: E501
        :type: bool
        """

        self._initialized = initialized

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessageOptionsOrBuilder, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessageOptionsOrBuilder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
