# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class NamePart(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unknown_fields': 'UnknownFieldSet',
        'name_part': 'str',
        'name_part_bytes': 'ByteString',
        'is_extension': 'bool',
        'default_instance_for_type': 'NamePart',
        'parser_for_type': 'ParserNamePart',
        'serialized_size': 'int',
        'initialized': 'bool',
        'initialization_error_string': 'str',
        'descriptor_for_type': 'Descriptor',
        'all_fields': 'dict(str, object)',
        'memoized_serialized_size': 'int'
    }

    attribute_map = {
        'unknown_fields': 'unknownFields',
        'name_part': 'namePart',
        'name_part_bytes': 'namePartBytes',
        'is_extension': 'isExtension',
        'default_instance_for_type': 'defaultInstanceForType',
        'parser_for_type': 'parserForType',
        'serialized_size': 'serializedSize',
        'initialized': 'initialized',
        'initialization_error_string': 'initializationErrorString',
        'descriptor_for_type': 'descriptorForType',
        'all_fields': 'allFields',
        'memoized_serialized_size': 'memoizedSerializedSize'
    }

    def __init__(self, unknown_fields=None, name_part=None, name_part_bytes=None, is_extension=None, default_instance_for_type=None, parser_for_type=None, serialized_size=None, initialized=None, initialization_error_string=None, descriptor_for_type=None, all_fields=None, memoized_serialized_size=None):  # noqa: E501
        """NamePart - a model defined in Swagger"""  # noqa: E501
        self._unknown_fields = None
        self._name_part = None
        self._name_part_bytes = None
        self._is_extension = None
        self._default_instance_for_type = None
        self._parser_for_type = None
        self._serialized_size = None
        self._initialized = None
        self._initialization_error_string = None
        self._descriptor_for_type = None
        self._all_fields = None
        self._memoized_serialized_size = None
        self.discriminator = None
        if unknown_fields is not None:
            self.unknown_fields = unknown_fields
        if name_part is not None:
            self.name_part = name_part
        if name_part_bytes is not None:
            self.name_part_bytes = name_part_bytes
        if is_extension is not None:
            self.is_extension = is_extension
        if default_instance_for_type is not None:
            self.default_instance_for_type = default_instance_for_type
        if parser_for_type is not None:
            self.parser_for_type = parser_for_type
        if serialized_size is not None:
            self.serialized_size = serialized_size
        if initialized is not None:
            self.initialized = initialized
        if initialization_error_string is not None:
            self.initialization_error_string = initialization_error_string
        if descriptor_for_type is not None:
            self.descriptor_for_type = descriptor_for_type
        if all_fields is not None:
            self.all_fields = all_fields
        if memoized_serialized_size is not None:
            self.memoized_serialized_size = memoized_serialized_size

    @property
    def unknown_fields(self):
        """Gets the unknown_fields of this NamePart.  # noqa: E501


        :return: The unknown_fields of this NamePart.  # noqa: E501
        :rtype: UnknownFieldSet
        """
        return self._unknown_fields

    @unknown_fields.setter
    def unknown_fields(self, unknown_fields):
        """Sets the unknown_fields of this NamePart.


        :param unknown_fields: The unknown_fields of this NamePart.  # noqa: E501
        :type: UnknownFieldSet
        """

        self._unknown_fields = unknown_fields

    @property
    def name_part(self):
        """Gets the name_part of this NamePart.  # noqa: E501


        :return: The name_part of this NamePart.  # noqa: E501
        :rtype: str
        """
        return self._name_part

    @name_part.setter
    def name_part(self, name_part):
        """Sets the name_part of this NamePart.


        :param name_part: The name_part of this NamePart.  # noqa: E501
        :type: str
        """

        self._name_part = name_part

    @property
    def name_part_bytes(self):
        """Gets the name_part_bytes of this NamePart.  # noqa: E501


        :return: The name_part_bytes of this NamePart.  # noqa: E501
        :rtype: ByteString
        """
        return self._name_part_bytes

    @name_part_bytes.setter
    def name_part_bytes(self, name_part_bytes):
        """Sets the name_part_bytes of this NamePart.


        :param name_part_bytes: The name_part_bytes of this NamePart.  # noqa: E501
        :type: ByteString
        """

        self._name_part_bytes = name_part_bytes

    @property
    def is_extension(self):
        """Gets the is_extension of this NamePart.  # noqa: E501


        :return: The is_extension of this NamePart.  # noqa: E501
        :rtype: bool
        """
        return self._is_extension

    @is_extension.setter
    def is_extension(self, is_extension):
        """Sets the is_extension of this NamePart.


        :param is_extension: The is_extension of this NamePart.  # noqa: E501
        :type: bool
        """

        self._is_extension = is_extension

    @property
    def default_instance_for_type(self):
        """Gets the default_instance_for_type of this NamePart.  # noqa: E501


        :return: The default_instance_for_type of this NamePart.  # noqa: E501
        :rtype: NamePart
        """
        return self._default_instance_for_type

    @default_instance_for_type.setter
    def default_instance_for_type(self, default_instance_for_type):
        """Sets the default_instance_for_type of this NamePart.


        :param default_instance_for_type: The default_instance_for_type of this NamePart.  # noqa: E501
        :type: NamePart
        """

        self._default_instance_for_type = default_instance_for_type

    @property
    def parser_for_type(self):
        """Gets the parser_for_type of this NamePart.  # noqa: E501


        :return: The parser_for_type of this NamePart.  # noqa: E501
        :rtype: ParserNamePart
        """
        return self._parser_for_type

    @parser_for_type.setter
    def parser_for_type(self, parser_for_type):
        """Sets the parser_for_type of this NamePart.


        :param parser_for_type: The parser_for_type of this NamePart.  # noqa: E501
        :type: ParserNamePart
        """

        self._parser_for_type = parser_for_type

    @property
    def serialized_size(self):
        """Gets the serialized_size of this NamePart.  # noqa: E501


        :return: The serialized_size of this NamePart.  # noqa: E501
        :rtype: int
        """
        return self._serialized_size

    @serialized_size.setter
    def serialized_size(self, serialized_size):
        """Sets the serialized_size of this NamePart.


        :param serialized_size: The serialized_size of this NamePart.  # noqa: E501
        :type: int
        """

        self._serialized_size = serialized_size

    @property
    def initialized(self):
        """Gets the initialized of this NamePart.  # noqa: E501


        :return: The initialized of this NamePart.  # noqa: E501
        :rtype: bool
        """
        return self._initialized

    @initialized.setter
    def initialized(self, initialized):
        """Sets the initialized of this NamePart.


        :param initialized: The initialized of this NamePart.  # noqa: E501
        :type: bool
        """

        self._initialized = initialized

    @property
    def initialization_error_string(self):
        """Gets the initialization_error_string of this NamePart.  # noqa: E501


        :return: The initialization_error_string of this NamePart.  # noqa: E501
        :rtype: str
        """
        return self._initialization_error_string

    @initialization_error_string.setter
    def initialization_error_string(self, initialization_error_string):
        """Sets the initialization_error_string of this NamePart.


        :param initialization_error_string: The initialization_error_string of this NamePart.  # noqa: E501
        :type: str
        """

        self._initialization_error_string = initialization_error_string

    @property
    def descriptor_for_type(self):
        """Gets the descriptor_for_type of this NamePart.  # noqa: E501


        :return: The descriptor_for_type of this NamePart.  # noqa: E501
        :rtype: Descriptor
        """
        return self._descriptor_for_type

    @descriptor_for_type.setter
    def descriptor_for_type(self, descriptor_for_type):
        """Sets the descriptor_for_type of this NamePart.


        :param descriptor_for_type: The descriptor_for_type of this NamePart.  # noqa: E501
        :type: Descriptor
        """

        self._descriptor_for_type = descriptor_for_type

    @property
    def all_fields(self):
        """Gets the all_fields of this NamePart.  # noqa: E501


        :return: The all_fields of this NamePart.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._all_fields

    @all_fields.setter
    def all_fields(self, all_fields):
        """Sets the all_fields of this NamePart.


        :param all_fields: The all_fields of this NamePart.  # noqa: E501
        :type: dict(str, object)
        """

        self._all_fields = all_fields

    @property
    def memoized_serialized_size(self):
        """Gets the memoized_serialized_size of this NamePart.  # noqa: E501


        :return: The memoized_serialized_size of this NamePart.  # noqa: E501
        :rtype: int
        """
        return self._memoized_serialized_size

    @memoized_serialized_size.setter
    def memoized_serialized_size(self, memoized_serialized_size):
        """Sets the memoized_serialized_size of this NamePart.


        :param memoized_serialized_size: The memoized_serialized_size of this NamePart.  # noqa: E501
        :type: int
        """

        self._memoized_serialized_size = memoized_serialized_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NamePart, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NamePart):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
