# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OneofDescriptor(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'index': 'int',
        'proto': 'OneofDescriptorProto',
        'full_name': 'str',
        'file': 'FileDescriptor',
        'containing_type': 'Descriptor',
        'field_count': 'int',
        'fields': 'list[FieldDescriptor]',
        'options': 'OneofOptions',
        'name': 'str',
        'synthetic': 'bool'
    }

    attribute_map = {
        'index': 'index',
        'proto': 'proto',
        'full_name': 'fullName',
        'file': 'file',
        'containing_type': 'containingType',
        'field_count': 'fieldCount',
        'fields': 'fields',
        'options': 'options',
        'name': 'name',
        'synthetic': 'synthetic'
    }

    def __init__(self, index=None, proto=None, full_name=None, file=None, containing_type=None, field_count=None, fields=None, options=None, name=None, synthetic=None):  # noqa: E501
        """OneofDescriptor - a model defined in Swagger"""  # noqa: E501
        self._index = None
        self._proto = None
        self._full_name = None
        self._file = None
        self._containing_type = None
        self._field_count = None
        self._fields = None
        self._options = None
        self._name = None
        self._synthetic = None
        self.discriminator = None
        if index is not None:
            self.index = index
        if proto is not None:
            self.proto = proto
        if full_name is not None:
            self.full_name = full_name
        if file is not None:
            self.file = file
        if containing_type is not None:
            self.containing_type = containing_type
        if field_count is not None:
            self.field_count = field_count
        if fields is not None:
            self.fields = fields
        if options is not None:
            self.options = options
        if name is not None:
            self.name = name
        if synthetic is not None:
            self.synthetic = synthetic

    @property
    def index(self):
        """Gets the index of this OneofDescriptor.  # noqa: E501


        :return: The index of this OneofDescriptor.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this OneofDescriptor.


        :param index: The index of this OneofDescriptor.  # noqa: E501
        :type: int
        """

        self._index = index

    @property
    def proto(self):
        """Gets the proto of this OneofDescriptor.  # noqa: E501


        :return: The proto of this OneofDescriptor.  # noqa: E501
        :rtype: OneofDescriptorProto
        """
        return self._proto

    @proto.setter
    def proto(self, proto):
        """Sets the proto of this OneofDescriptor.


        :param proto: The proto of this OneofDescriptor.  # noqa: E501
        :type: OneofDescriptorProto
        """

        self._proto = proto

    @property
    def full_name(self):
        """Gets the full_name of this OneofDescriptor.  # noqa: E501


        :return: The full_name of this OneofDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this OneofDescriptor.


        :param full_name: The full_name of this OneofDescriptor.  # noqa: E501
        :type: str
        """

        self._full_name = full_name

    @property
    def file(self):
        """Gets the file of this OneofDescriptor.  # noqa: E501


        :return: The file of this OneofDescriptor.  # noqa: E501
        :rtype: FileDescriptor
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this OneofDescriptor.


        :param file: The file of this OneofDescriptor.  # noqa: E501
        :type: FileDescriptor
        """

        self._file = file

    @property
    def containing_type(self):
        """Gets the containing_type of this OneofDescriptor.  # noqa: E501


        :return: The containing_type of this OneofDescriptor.  # noqa: E501
        :rtype: Descriptor
        """
        return self._containing_type

    @containing_type.setter
    def containing_type(self, containing_type):
        """Sets the containing_type of this OneofDescriptor.


        :param containing_type: The containing_type of this OneofDescriptor.  # noqa: E501
        :type: Descriptor
        """

        self._containing_type = containing_type

    @property
    def field_count(self):
        """Gets the field_count of this OneofDescriptor.  # noqa: E501


        :return: The field_count of this OneofDescriptor.  # noqa: E501
        :rtype: int
        """
        return self._field_count

    @field_count.setter
    def field_count(self, field_count):
        """Sets the field_count of this OneofDescriptor.


        :param field_count: The field_count of this OneofDescriptor.  # noqa: E501
        :type: int
        """

        self._field_count = field_count

    @property
    def fields(self):
        """Gets the fields of this OneofDescriptor.  # noqa: E501


        :return: The fields of this OneofDescriptor.  # noqa: E501
        :rtype: list[FieldDescriptor]
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this OneofDescriptor.


        :param fields: The fields of this OneofDescriptor.  # noqa: E501
        :type: list[FieldDescriptor]
        """

        self._fields = fields

    @property
    def options(self):
        """Gets the options of this OneofDescriptor.  # noqa: E501


        :return: The options of this OneofDescriptor.  # noqa: E501
        :rtype: OneofOptions
        """
        return self._options

    @options.setter
    def options(self, options):
        """Sets the options of this OneofDescriptor.


        :param options: The options of this OneofDescriptor.  # noqa: E501
        :type: OneofOptions
        """

        self._options = options

    @property
    def name(self):
        """Gets the name of this OneofDescriptor.  # noqa: E501


        :return: The name of this OneofDescriptor.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OneofDescriptor.


        :param name: The name of this OneofDescriptor.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def synthetic(self):
        """Gets the synthetic of this OneofDescriptor.  # noqa: E501


        :return: The synthetic of this OneofDescriptor.  # noqa: E501
        :rtype: bool
        """
        return self._synthetic

    @synthetic.setter
    def synthetic(self, synthetic):
        """Sets the synthetic of this OneofDescriptor.


        :param synthetic: The synthetic of this OneofDescriptor.  # noqa: E501
        :type: bool
        """

        self._synthetic = synthetic

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OneofDescriptor, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OneofDescriptor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
