# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SourceCodeInfoOrBuilder(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'location_or_builder_list': 'list[LocationOrBuilder]',
        'location_list': 'list[Location]',
        'location_count': 'int',
        'initialization_error_string': 'str',
        'descriptor_for_type': 'Descriptor',
        'all_fields': 'dict(str, object)',
        'default_instance_for_type': 'Message',
        'unknown_fields': 'UnknownFieldSet',
        'initialized': 'bool'
    }

    attribute_map = {
        'location_or_builder_list': 'locationOrBuilderList',
        'location_list': 'locationList',
        'location_count': 'locationCount',
        'initialization_error_string': 'initializationErrorString',
        'descriptor_for_type': 'descriptorForType',
        'all_fields': 'allFields',
        'default_instance_for_type': 'defaultInstanceForType',
        'unknown_fields': 'unknownFields',
        'initialized': 'initialized'
    }

    def __init__(self, location_or_builder_list=None, location_list=None, location_count=None, initialization_error_string=None, descriptor_for_type=None, all_fields=None, default_instance_for_type=None, unknown_fields=None, initialized=None):  # noqa: E501
        """SourceCodeInfoOrBuilder - a model defined in Swagger"""  # noqa: E501
        self._location_or_builder_list = None
        self._location_list = None
        self._location_count = None
        self._initialization_error_string = None
        self._descriptor_for_type = None
        self._all_fields = None
        self._default_instance_for_type = None
        self._unknown_fields = None
        self._initialized = None
        self.discriminator = None
        if location_or_builder_list is not None:
            self.location_or_builder_list = location_or_builder_list
        if location_list is not None:
            self.location_list = location_list
        if location_count is not None:
            self.location_count = location_count
        if initialization_error_string is not None:
            self.initialization_error_string = initialization_error_string
        if descriptor_for_type is not None:
            self.descriptor_for_type = descriptor_for_type
        if all_fields is not None:
            self.all_fields = all_fields
        if default_instance_for_type is not None:
            self.default_instance_for_type = default_instance_for_type
        if unknown_fields is not None:
            self.unknown_fields = unknown_fields
        if initialized is not None:
            self.initialized = initialized

    @property
    def location_or_builder_list(self):
        """Gets the location_or_builder_list of this SourceCodeInfoOrBuilder.  # noqa: E501


        :return: The location_or_builder_list of this SourceCodeInfoOrBuilder.  # noqa: E501
        :rtype: list[LocationOrBuilder]
        """
        return self._location_or_builder_list

    @location_or_builder_list.setter
    def location_or_builder_list(self, location_or_builder_list):
        """Sets the location_or_builder_list of this SourceCodeInfoOrBuilder.


        :param location_or_builder_list: The location_or_builder_list of this SourceCodeInfoOrBuilder.  # noqa: E501
        :type: list[LocationOrBuilder]
        """

        self._location_or_builder_list = location_or_builder_list

    @property
    def location_list(self):
        """Gets the location_list of this SourceCodeInfoOrBuilder.  # noqa: E501


        :return: The location_list of this SourceCodeInfoOrBuilder.  # noqa: E501
        :rtype: list[Location]
        """
        return self._location_list

    @location_list.setter
    def location_list(self, location_list):
        """Sets the location_list of this SourceCodeInfoOrBuilder.


        :param location_list: The location_list of this SourceCodeInfoOrBuilder.  # noqa: E501
        :type: list[Location]
        """

        self._location_list = location_list

    @property
    def location_count(self):
        """Gets the location_count of this SourceCodeInfoOrBuilder.  # noqa: E501


        :return: The location_count of this SourceCodeInfoOrBuilder.  # noqa: E501
        :rtype: int
        """
        return self._location_count

    @location_count.setter
    def location_count(self, location_count):
        """Sets the location_count of this SourceCodeInfoOrBuilder.


        :param location_count: The location_count of this SourceCodeInfoOrBuilder.  # noqa: E501
        :type: int
        """

        self._location_count = location_count

    @property
    def initialization_error_string(self):
        """Gets the initialization_error_string of this SourceCodeInfoOrBuilder.  # noqa: E501


        :return: The initialization_error_string of this SourceCodeInfoOrBuilder.  # noqa: E501
        :rtype: str
        """
        return self._initialization_error_string

    @initialization_error_string.setter
    def initialization_error_string(self, initialization_error_string):
        """Sets the initialization_error_string of this SourceCodeInfoOrBuilder.


        :param initialization_error_string: The initialization_error_string of this SourceCodeInfoOrBuilder.  # noqa: E501
        :type: str
        """

        self._initialization_error_string = initialization_error_string

    @property
    def descriptor_for_type(self):
        """Gets the descriptor_for_type of this SourceCodeInfoOrBuilder.  # noqa: E501


        :return: The descriptor_for_type of this SourceCodeInfoOrBuilder.  # noqa: E501
        :rtype: Descriptor
        """
        return self._descriptor_for_type

    @descriptor_for_type.setter
    def descriptor_for_type(self, descriptor_for_type):
        """Sets the descriptor_for_type of this SourceCodeInfoOrBuilder.


        :param descriptor_for_type: The descriptor_for_type of this SourceCodeInfoOrBuilder.  # noqa: E501
        :type: Descriptor
        """

        self._descriptor_for_type = descriptor_for_type

    @property
    def all_fields(self):
        """Gets the all_fields of this SourceCodeInfoOrBuilder.  # noqa: E501


        :return: The all_fields of this SourceCodeInfoOrBuilder.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._all_fields

    @all_fields.setter
    def all_fields(self, all_fields):
        """Sets the all_fields of this SourceCodeInfoOrBuilder.


        :param all_fields: The all_fields of this SourceCodeInfoOrBuilder.  # noqa: E501
        :type: dict(str, object)
        """

        self._all_fields = all_fields

    @property
    def default_instance_for_type(self):
        """Gets the default_instance_for_type of this SourceCodeInfoOrBuilder.  # noqa: E501


        :return: The default_instance_for_type of this SourceCodeInfoOrBuilder.  # noqa: E501
        :rtype: Message
        """
        return self._default_instance_for_type

    @default_instance_for_type.setter
    def default_instance_for_type(self, default_instance_for_type):
        """Sets the default_instance_for_type of this SourceCodeInfoOrBuilder.


        :param default_instance_for_type: The default_instance_for_type of this SourceCodeInfoOrBuilder.  # noqa: E501
        :type: Message
        """

        self._default_instance_for_type = default_instance_for_type

    @property
    def unknown_fields(self):
        """Gets the unknown_fields of this SourceCodeInfoOrBuilder.  # noqa: E501


        :return: The unknown_fields of this SourceCodeInfoOrBuilder.  # noqa: E501
        :rtype: UnknownFieldSet
        """
        return self._unknown_fields

    @unknown_fields.setter
    def unknown_fields(self, unknown_fields):
        """Sets the unknown_fields of this SourceCodeInfoOrBuilder.


        :param unknown_fields: The unknown_fields of this SourceCodeInfoOrBuilder.  # noqa: E501
        :type: UnknownFieldSet
        """

        self._unknown_fields = unknown_fields

    @property
    def initialized(self):
        """Gets the initialized of this SourceCodeInfoOrBuilder.  # noqa: E501


        :return: The initialized of this SourceCodeInfoOrBuilder.  # noqa: E501
        :rtype: bool
        """
        return self._initialized

    @initialized.setter
    def initialized(self, initialized):
        """Sets the initialized of this SourceCodeInfoOrBuilder.


        :param initialized: The initialized of this SourceCodeInfoOrBuilder.  # noqa: E501
        :type: bool
        """

        self._initialized = initialized

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SourceCodeInfoOrBuilder, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SourceCodeInfoOrBuilder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
