# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TaskMock(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'output': 'dict(str, object)',
        'execution_time': 'int',
        'queue_wait_time': 'int'
    }

    attribute_map = {
        'status': 'status',
        'output': 'output',
        'execution_time': 'executionTime',
        'queue_wait_time': 'queueWaitTime'
    }

    def __init__(self, status=None, output=None, execution_time=None, queue_wait_time=None):  # noqa: E501
        """TaskMock - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._output = None
        self._execution_time = None
        self._queue_wait_time = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if output is not None:
            self.output = output
        if execution_time is not None:
            self.execution_time = execution_time
        if queue_wait_time is not None:
            self.queue_wait_time = queue_wait_time

    @property
    def status(self):
        """Gets the status of this TaskMock.  # noqa: E501


        :return: The status of this TaskMock.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TaskMock.


        :param status: The status of this TaskMock.  # noqa: E501
        :type: str
        """
        allowed_values = ["IN_PROGRESS", "FAILED", "FAILED_WITH_TERMINAL_ERROR", "COMPLETED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def output(self):
        """Gets the output of this TaskMock.  # noqa: E501


        :return: The output of this TaskMock.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TaskMock.


        :param output: The output of this TaskMock.  # noqa: E501
        :type: dict(str, object)
        """

        self._output = output

    @property
    def execution_time(self):
        """Gets the execution_time of this TaskMock.  # noqa: E501


        :return: The execution_time of this TaskMock.  # noqa: E501
        :rtype: int
        """
        return self._execution_time

    @execution_time.setter
    def execution_time(self, execution_time):
        """Sets the execution_time of this TaskMock.


        :param execution_time: The execution_time of this TaskMock.  # noqa: E501
        :type: int
        """

        self._execution_time = execution_time

    @property
    def queue_wait_time(self):
        """Gets the queue_wait_time of this TaskMock.  # noqa: E501


        :return: The queue_wait_time of this TaskMock.  # noqa: E501
        :rtype: int
        """
        return self._queue_wait_time

    @queue_wait_time.setter
    def queue_wait_time(self, queue_wait_time):
        """Sets the queue_wait_time of this TaskMock.


        :param queue_wait_time: The queue_wait_time of this TaskMock.  # noqa: E501
        :type: int
        """

        self._queue_wait_time = queue_wait_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TaskMock, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TaskMock):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
