# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UninterpretedOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'unknown_fields': 'UnknownFieldSet',
        'name_or_builder_list': 'list[NamePartOrBuilder]',
        'identifier_value_bytes': 'ByteString',
        'positive_int_value': 'int',
        'negative_int_value': 'int',
        'aggregate_value_bytes': 'ByteString',
        'name_list': 'list[NamePart]',
        'identifier_value': 'str',
        'aggregate_value': 'str',
        'default_instance_for_type': 'UninterpretedOption',
        'parser_for_type': 'ParserUninterpretedOption',
        'serialized_size': 'int',
        'double_value': 'float',
        'string_value': 'ByteString',
        'initialized': 'bool',
        'name_count': 'int',
        'initialization_error_string': 'str',
        'descriptor_for_type': 'Descriptor',
        'all_fields': 'dict(str, object)',
        'memoized_serialized_size': 'int'
    }

    attribute_map = {
        'unknown_fields': 'unknownFields',
        'name_or_builder_list': 'nameOrBuilderList',
        'identifier_value_bytes': 'identifierValueBytes',
        'positive_int_value': 'positiveIntValue',
        'negative_int_value': 'negativeIntValue',
        'aggregate_value_bytes': 'aggregateValueBytes',
        'name_list': 'nameList',
        'identifier_value': 'identifierValue',
        'aggregate_value': 'aggregateValue',
        'default_instance_for_type': 'defaultInstanceForType',
        'parser_for_type': 'parserForType',
        'serialized_size': 'serializedSize',
        'double_value': 'doubleValue',
        'string_value': 'stringValue',
        'initialized': 'initialized',
        'name_count': 'nameCount',
        'initialization_error_string': 'initializationErrorString',
        'descriptor_for_type': 'descriptorForType',
        'all_fields': 'allFields',
        'memoized_serialized_size': 'memoizedSerializedSize'
    }

    def __init__(self, unknown_fields=None, name_or_builder_list=None, identifier_value_bytes=None, positive_int_value=None, negative_int_value=None, aggregate_value_bytes=None, name_list=None, identifier_value=None, aggregate_value=None, default_instance_for_type=None, parser_for_type=None, serialized_size=None, double_value=None, string_value=None, initialized=None, name_count=None, initialization_error_string=None, descriptor_for_type=None, all_fields=None, memoized_serialized_size=None):  # noqa: E501
        """UninterpretedOption - a model defined in Swagger"""  # noqa: E501
        self._unknown_fields = None
        self._name_or_builder_list = None
        self._identifier_value_bytes = None
        self._positive_int_value = None
        self._negative_int_value = None
        self._aggregate_value_bytes = None
        self._name_list = None
        self._identifier_value = None
        self._aggregate_value = None
        self._default_instance_for_type = None
        self._parser_for_type = None
        self._serialized_size = None
        self._double_value = None
        self._string_value = None
        self._initialized = None
        self._name_count = None
        self._initialization_error_string = None
        self._descriptor_for_type = None
        self._all_fields = None
        self._memoized_serialized_size = None
        self.discriminator = None
        if unknown_fields is not None:
            self.unknown_fields = unknown_fields
        if name_or_builder_list is not None:
            self.name_or_builder_list = name_or_builder_list
        if identifier_value_bytes is not None:
            self.identifier_value_bytes = identifier_value_bytes
        if positive_int_value is not None:
            self.positive_int_value = positive_int_value
        if negative_int_value is not None:
            self.negative_int_value = negative_int_value
        if aggregate_value_bytes is not None:
            self.aggregate_value_bytes = aggregate_value_bytes
        if name_list is not None:
            self.name_list = name_list
        if identifier_value is not None:
            self.identifier_value = identifier_value
        if aggregate_value is not None:
            self.aggregate_value = aggregate_value
        if default_instance_for_type is not None:
            self.default_instance_for_type = default_instance_for_type
        if parser_for_type is not None:
            self.parser_for_type = parser_for_type
        if serialized_size is not None:
            self.serialized_size = serialized_size
        if double_value is not None:
            self.double_value = double_value
        if string_value is not None:
            self.string_value = string_value
        if initialized is not None:
            self.initialized = initialized
        if name_count is not None:
            self.name_count = name_count
        if initialization_error_string is not None:
            self.initialization_error_string = initialization_error_string
        if descriptor_for_type is not None:
            self.descriptor_for_type = descriptor_for_type
        if all_fields is not None:
            self.all_fields = all_fields
        if memoized_serialized_size is not None:
            self.memoized_serialized_size = memoized_serialized_size

    @property
    def unknown_fields(self):
        """Gets the unknown_fields of this UninterpretedOption.  # noqa: E501


        :return: The unknown_fields of this UninterpretedOption.  # noqa: E501
        :rtype: UnknownFieldSet
        """
        return self._unknown_fields

    @unknown_fields.setter
    def unknown_fields(self, unknown_fields):
        """Sets the unknown_fields of this UninterpretedOption.


        :param unknown_fields: The unknown_fields of this UninterpretedOption.  # noqa: E501
        :type: UnknownFieldSet
        """

        self._unknown_fields = unknown_fields

    @property
    def name_or_builder_list(self):
        """Gets the name_or_builder_list of this UninterpretedOption.  # noqa: E501


        :return: The name_or_builder_list of this UninterpretedOption.  # noqa: E501
        :rtype: list[NamePartOrBuilder]
        """
        return self._name_or_builder_list

    @name_or_builder_list.setter
    def name_or_builder_list(self, name_or_builder_list):
        """Sets the name_or_builder_list of this UninterpretedOption.


        :param name_or_builder_list: The name_or_builder_list of this UninterpretedOption.  # noqa: E501
        :type: list[NamePartOrBuilder]
        """

        self._name_or_builder_list = name_or_builder_list

    @property
    def identifier_value_bytes(self):
        """Gets the identifier_value_bytes of this UninterpretedOption.  # noqa: E501


        :return: The identifier_value_bytes of this UninterpretedOption.  # noqa: E501
        :rtype: ByteString
        """
        return self._identifier_value_bytes

    @identifier_value_bytes.setter
    def identifier_value_bytes(self, identifier_value_bytes):
        """Sets the identifier_value_bytes of this UninterpretedOption.


        :param identifier_value_bytes: The identifier_value_bytes of this UninterpretedOption.  # noqa: E501
        :type: ByteString
        """

        self._identifier_value_bytes = identifier_value_bytes

    @property
    def positive_int_value(self):
        """Gets the positive_int_value of this UninterpretedOption.  # noqa: E501


        :return: The positive_int_value of this UninterpretedOption.  # noqa: E501
        :rtype: int
        """
        return self._positive_int_value

    @positive_int_value.setter
    def positive_int_value(self, positive_int_value):
        """Sets the positive_int_value of this UninterpretedOption.


        :param positive_int_value: The positive_int_value of this UninterpretedOption.  # noqa: E501
        :type: int
        """

        self._positive_int_value = positive_int_value

    @property
    def negative_int_value(self):
        """Gets the negative_int_value of this UninterpretedOption.  # noqa: E501


        :return: The negative_int_value of this UninterpretedOption.  # noqa: E501
        :rtype: int
        """
        return self._negative_int_value

    @negative_int_value.setter
    def negative_int_value(self, negative_int_value):
        """Sets the negative_int_value of this UninterpretedOption.


        :param negative_int_value: The negative_int_value of this UninterpretedOption.  # noqa: E501
        :type: int
        """

        self._negative_int_value = negative_int_value

    @property
    def aggregate_value_bytes(self):
        """Gets the aggregate_value_bytes of this UninterpretedOption.  # noqa: E501


        :return: The aggregate_value_bytes of this UninterpretedOption.  # noqa: E501
        :rtype: ByteString
        """
        return self._aggregate_value_bytes

    @aggregate_value_bytes.setter
    def aggregate_value_bytes(self, aggregate_value_bytes):
        """Sets the aggregate_value_bytes of this UninterpretedOption.


        :param aggregate_value_bytes: The aggregate_value_bytes of this UninterpretedOption.  # noqa: E501
        :type: ByteString
        """

        self._aggregate_value_bytes = aggregate_value_bytes

    @property
    def name_list(self):
        """Gets the name_list of this UninterpretedOption.  # noqa: E501


        :return: The name_list of this UninterpretedOption.  # noqa: E501
        :rtype: list[NamePart]
        """
        return self._name_list

    @name_list.setter
    def name_list(self, name_list):
        """Sets the name_list of this UninterpretedOption.


        :param name_list: The name_list of this UninterpretedOption.  # noqa: E501
        :type: list[NamePart]
        """

        self._name_list = name_list

    @property
    def identifier_value(self):
        """Gets the identifier_value of this UninterpretedOption.  # noqa: E501


        :return: The identifier_value of this UninterpretedOption.  # noqa: E501
        :rtype: str
        """
        return self._identifier_value

    @identifier_value.setter
    def identifier_value(self, identifier_value):
        """Sets the identifier_value of this UninterpretedOption.


        :param identifier_value: The identifier_value of this UninterpretedOption.  # noqa: E501
        :type: str
        """

        self._identifier_value = identifier_value

    @property
    def aggregate_value(self):
        """Gets the aggregate_value of this UninterpretedOption.  # noqa: E501


        :return: The aggregate_value of this UninterpretedOption.  # noqa: E501
        :rtype: str
        """
        return self._aggregate_value

    @aggregate_value.setter
    def aggregate_value(self, aggregate_value):
        """Sets the aggregate_value of this UninterpretedOption.


        :param aggregate_value: The aggregate_value of this UninterpretedOption.  # noqa: E501
        :type: str
        """

        self._aggregate_value = aggregate_value

    @property
    def default_instance_for_type(self):
        """Gets the default_instance_for_type of this UninterpretedOption.  # noqa: E501


        :return: The default_instance_for_type of this UninterpretedOption.  # noqa: E501
        :rtype: UninterpretedOption
        """
        return self._default_instance_for_type

    @default_instance_for_type.setter
    def default_instance_for_type(self, default_instance_for_type):
        """Sets the default_instance_for_type of this UninterpretedOption.


        :param default_instance_for_type: The default_instance_for_type of this UninterpretedOption.  # noqa: E501
        :type: UninterpretedOption
        """

        self._default_instance_for_type = default_instance_for_type

    @property
    def parser_for_type(self):
        """Gets the parser_for_type of this UninterpretedOption.  # noqa: E501


        :return: The parser_for_type of this UninterpretedOption.  # noqa: E501
        :rtype: ParserUninterpretedOption
        """
        return self._parser_for_type

    @parser_for_type.setter
    def parser_for_type(self, parser_for_type):
        """Sets the parser_for_type of this UninterpretedOption.


        :param parser_for_type: The parser_for_type of this UninterpretedOption.  # noqa: E501
        :type: ParserUninterpretedOption
        """

        self._parser_for_type = parser_for_type

    @property
    def serialized_size(self):
        """Gets the serialized_size of this UninterpretedOption.  # noqa: E501


        :return: The serialized_size of this UninterpretedOption.  # noqa: E501
        :rtype: int
        """
        return self._serialized_size

    @serialized_size.setter
    def serialized_size(self, serialized_size):
        """Sets the serialized_size of this UninterpretedOption.


        :param serialized_size: The serialized_size of this UninterpretedOption.  # noqa: E501
        :type: int
        """

        self._serialized_size = serialized_size

    @property
    def double_value(self):
        """Gets the double_value of this UninterpretedOption.  # noqa: E501


        :return: The double_value of this UninterpretedOption.  # noqa: E501
        :rtype: float
        """
        return self._double_value

    @double_value.setter
    def double_value(self, double_value):
        """Sets the double_value of this UninterpretedOption.


        :param double_value: The double_value of this UninterpretedOption.  # noqa: E501
        :type: float
        """

        self._double_value = double_value

    @property
    def string_value(self):
        """Gets the string_value of this UninterpretedOption.  # noqa: E501


        :return: The string_value of this UninterpretedOption.  # noqa: E501
        :rtype: ByteString
        """
        return self._string_value

    @string_value.setter
    def string_value(self, string_value):
        """Sets the string_value of this UninterpretedOption.


        :param string_value: The string_value of this UninterpretedOption.  # noqa: E501
        :type: ByteString
        """

        self._string_value = string_value

    @property
    def initialized(self):
        """Gets the initialized of this UninterpretedOption.  # noqa: E501


        :return: The initialized of this UninterpretedOption.  # noqa: E501
        :rtype: bool
        """
        return self._initialized

    @initialized.setter
    def initialized(self, initialized):
        """Sets the initialized of this UninterpretedOption.


        :param initialized: The initialized of this UninterpretedOption.  # noqa: E501
        :type: bool
        """

        self._initialized = initialized

    @property
    def name_count(self):
        """Gets the name_count of this UninterpretedOption.  # noqa: E501


        :return: The name_count of this UninterpretedOption.  # noqa: E501
        :rtype: int
        """
        return self._name_count

    @name_count.setter
    def name_count(self, name_count):
        """Sets the name_count of this UninterpretedOption.


        :param name_count: The name_count of this UninterpretedOption.  # noqa: E501
        :type: int
        """

        self._name_count = name_count

    @property
    def initialization_error_string(self):
        """Gets the initialization_error_string of this UninterpretedOption.  # noqa: E501


        :return: The initialization_error_string of this UninterpretedOption.  # noqa: E501
        :rtype: str
        """
        return self._initialization_error_string

    @initialization_error_string.setter
    def initialization_error_string(self, initialization_error_string):
        """Sets the initialization_error_string of this UninterpretedOption.


        :param initialization_error_string: The initialization_error_string of this UninterpretedOption.  # noqa: E501
        :type: str
        """

        self._initialization_error_string = initialization_error_string

    @property
    def descriptor_for_type(self):
        """Gets the descriptor_for_type of this UninterpretedOption.  # noqa: E501


        :return: The descriptor_for_type of this UninterpretedOption.  # noqa: E501
        :rtype: Descriptor
        """
        return self._descriptor_for_type

    @descriptor_for_type.setter
    def descriptor_for_type(self, descriptor_for_type):
        """Sets the descriptor_for_type of this UninterpretedOption.


        :param descriptor_for_type: The descriptor_for_type of this UninterpretedOption.  # noqa: E501
        :type: Descriptor
        """

        self._descriptor_for_type = descriptor_for_type

    @property
    def all_fields(self):
        """Gets the all_fields of this UninterpretedOption.  # noqa: E501


        :return: The all_fields of this UninterpretedOption.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._all_fields

    @all_fields.setter
    def all_fields(self, all_fields):
        """Sets the all_fields of this UninterpretedOption.


        :param all_fields: The all_fields of this UninterpretedOption.  # noqa: E501
        :type: dict(str, object)
        """

        self._all_fields = all_fields

    @property
    def memoized_serialized_size(self):
        """Gets the memoized_serialized_size of this UninterpretedOption.  # noqa: E501


        :return: The memoized_serialized_size of this UninterpretedOption.  # noqa: E501
        :rtype: int
        """
        return self._memoized_serialized_size

    @memoized_serialized_size.setter
    def memoized_serialized_size(self, memoized_serialized_size):
        """Sets the memoized_serialized_size of this UninterpretedOption.


        :param memoized_serialized_size: The memoized_serialized_size of this UninterpretedOption.  # noqa: E501
        :type: int
        """

        self._memoized_serialized_size = memoized_serialized_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UninterpretedOption, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UninterpretedOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
