name: Continuous Delivery

on:
  release:
    types: [published]

jobs:
  publish-release-at-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish
        run: >
          DOCKER_BUILDKIT=1 docker build
          --progress=plain
          --build-arg CONDUCTOR_PYTHON_VERSION=${{ github.ref_name }}
          --build-arg PYPI_USER=${{ secrets.pypi_user }}
          --build-arg PYPI_PASS=${{ secrets.pypi_pass }}
          --target=publish     
          .
  wait-for-package-to-become-available-at-pypi:
    needs: publish-release-at-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Wait for package to become available at pypi
        run: sleep 300
  validate-release:
    needs: wait-for-package-to-become-available-at-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: >
          DOCKER_BUILDKIT=1 docker build
          --progress=plain
          --build-arg KEY=${{ secrets.KEY }}
          --build-arg SECRET=${{ secrets.SECRET }}
          --build-arg CONDUCTOR_SERVER_URL=${{ secrets.CONDUCTOR_SERVER_URL }}
          --build-arg CONDUCTOR_PYTHON_VERSION=${{ github.ref_name }}
          --build-arg SDK_ORIGIN=remote_sdk
          --target=test
          .
